# Generated by Django 4.1.5 on 2023-01-20 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prenotazioni', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prenotazione',
            fields=[
                ('priorità', models.DateTimeField()),
                ('ora_prenotata', models.DateTimeField(primary_key=True, serialize=False)),
                ('paglione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prenotazioni', to='prenotazioni.paglione')),
                ('utenti', models.ManyToManyField(related_name='prenotazioni', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Prenotazioni',
            },
        ),
    ]
