# Generated by Django 4.1.5 on 2023-01-20 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prenotazioni', '0002_prenotazione'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prenotazione',
            name='utenti',
        ),
        migrations.AddField(
            model_name='prenotazione',
            name='utente',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prenotazioni', to=settings.AUTH_USER_MODEL),
        ),
    ]
