# Generated by Django 4.1.5 on 2023-01-20 14:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prenotazioni', '0003_remove_prenotazione_utenti_prenotazione_utente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prenotazione',
            name='utente',
        ),
        migrations.AddField(
            model_name='prenotazione',
            name='utente',
            field=models.ManyToManyField(related_name='prenotazioni', to=settings.AUTH_USER_MODEL),
        ),
    ]
