# Generated by Django 4.1.5 on 2023-01-20 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prenotazioni', '0004_remove_prenotazione_utente_prenotazione_utente'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenotazione',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prenotazione',
            name='ora_prenotata',
            field=models.DateTimeField(),
        ),
        migrations.RemoveField(
            model_name='prenotazione',
            name='utente',
        ),
        migrations.AddField(
            model_name='prenotazione',
            name='utente',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prenotazioni', to=settings.AUTH_USER_MODEL),
        ),
    ]
