# Generated by Django 4.0 on 2023-01-26 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('prenotazioni', '0005_prenotazione_id_alter_prenotazione_ora_prenotata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancellazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ora_creazione', models.DateTimeField(auto_now_add=True)),
                ('messaggio', models.TextField()),
                ('prenotazione', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='prenotazioni.prenotazione')),
                ('utente', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancellazioni', to='auth.user')),
            ],
        ),
    ]
