# Generated by Django 4.0 on 2023-01-26 14:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazioni', '0007_alter_cancellazione_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancellazione',
            name='ora_creazione',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 26, 15, 13, 0, 499629)),
        ),
    ]
