# Generated by Django 4.0 on 2023-01-26 15:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazioni', '0009_alter_cancellazione_ora_creazione'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancellazione',
            name='ora_creazione',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 26, 16, 4, 3, 10991)),
        ),
    ]
