# Generated by Django 4.0 on 2023-01-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazioni', '0010_alter_cancellazione_ora_creazione'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancellazione',
            name='ora_creazione',
            field=models.DateTimeField(),
        ),
    ]
