# Generated by Django 4.1.2 on 2022-10-14 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libro',
            options={'verbose_name_plural': 'Libri'},
        ),
    ]
