# Generated by Django 4.0 on 2023-01-26 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ora_creazione', models.DateTimeField(auto_now_add=True)),
                ('messaggio', models.TextField()),
                ('immagine', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('creatore', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='auth.user')),
            ],
        ),
    ]
